import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import PostBox from "../Components/PostBox";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="max-w-5xl my-7 mx-auto">
      <Head>
        <title>Tonny's Reddit clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/**Post boxcomponent */}

      <PostBox />
      <div></div>
      <h1>This is a NExt App@@</h1>
    </div>
  );
};

export default Home;
